### ISSUE TITLE
26. 컨텐츠 미리보기 종료 시 '자동종료 및 상세화면'으로 이동하지 않음.

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#11]
[보고일자]
2015.11.11

[빌드버전]
0.4

[재현경로]
1. 미리보기 존재 하는 VOD 상세 페이지
2. 미리보기 실행
3. 미리보기 3분 종료 후 동작 확인

[예상결과]
미리보기 재생이 끝날경우 '자동종료 및 상세화면'으로 이동되어야함.

[현재증상]
컨텐츠 미리보기 종료 시 '자동종료 및 상세화면'으로 이동하지 않음.

**Comment by MinJaeHun** [comment]
[12.29] 플레이어 이슈는 주요 이슈사항 처리, 플레이어 제어 범위 검토 후 재협의

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
