### ISSUE TITLE
45. VOD 시청 중 홈 버튼 클릭 하여 바탕화면 이동 후 앱 재진입 시 이어보기 또는 처음부터 자동 재생되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#12]
[보고일자]
2015.11.12

[빌드버전]
0.5

[재현경로]
1. VOD 재생 중 스마트폰 홈버튼 클릭
2. 앱 재진입 후 영상 재생여부 및 재생 위치 확인

[예상결과]
처음부터 VOD 자동 재생 또는 시청중이던 화면이 유지 되어야 함
* 시나리오 협의 필요

[현재증상]
VOD 시청 중 홈 버튼 클릭 하여 바탕화면 이동 후 앱 재진입 시 이어보기 또는 처음부터 자동 재생되지 않음

**Comment by MinJaeHun** [comment]
[12.29] 플레이어 이슈는 주요 오류사항 처리 후 플레이어 제어 범위 검토하여 재협의

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
