### ISSUE TITLE
79. VOD 상세 페이지 내 많이 찾는 VOD 17~18회 이상 이동 시 많이 찾는 VOD 포스터 호출 시 딜레이 발생 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#14]
[보고일자]
2015.11.16

[빌드버전]
0.6

[재현경로]
1. VOD 상세 페이지
2. 많이 찾는 VOD 진입 (17~18회 이상)
3. 많이 찾는 VOD 포스터 호출 속도 확인

[예상결과]
VOD 상세 페이지 내 많이 찾는 VOD로 수회 이동하더라도 포스터 호출 시 딜레이 발생하지 않아야 함

[현재증상]
VOD 상세 페이지 내 많이 찾는 VOD 17~18회 이상 이동 시 많이 찾는 VOD 포스터 호출 시 딜레이 발생 함

**Comment by minkyuuuu** [comment]
원인 분석 필요

**Comment by MinJaeHun** [comment]
내용 잘못 입력되었습니다. 수정 필요합니다.

**Comment by MinJaeHun** [comment]
[12.29] 미팅을 통해 closing 결정 (캐스트이즈, GT)
