### ISSUE TITLE
69. 검색 페이지 내 검색결과 많을 경우 포스터 목록 호출되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#15]
[보고일자]
2015.11.16

[빌드버전]
0.6

[재현경로]
1. 검색 페이지
2. 임의의 검색어 입력 (ex : 가)
3. 검색 버튼 클릭 후 목록 확인

[예상결과]
검색 페이지 내 검색결과 많을 경우 포스터 목록 호출되어야 함
메모리 이슈일 경우 해결 방안 필요 함

[현재증상]
검색결과 많을 경우 목록 호출 불가

**Comment by minkyuuuu** [comment]
검색 API의 페이징 처리 필요

**Comment by Kimwoodam** [comment]
@MinJaeHun 서버쪽 API 추가 필요 항목입니다. 확인 부탁 드립니다.

**Comment by MinJaeHun** [comment]
[12.29] 대상 API 규격에 paging 처리 기준 있음. 캐스트이즈

**Comment by Kimwoodam** [comment]
@MinJaeHun  [16.01.07] API 문서 확인 하였습니다. 수정 진행중입니다.

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
