### ISSUE TITLE
85. 앱 내 모든 2depth 이상 페이지 화면 영역 내에서 좌에서 우로 Swipe 시 이전 페이지로 이동되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#16]
[보고일자]
2015.12.11

[빌드버전]
0.8

[재현경로]
1. 앱 내 모든 2depth 이상 페이지
(ex : VOD 상세페이지, 검색 페이지…)
2. 화면 영역 내에서 좌에서 우로 Swipe

[예상결과]
앱 내 모든 페이지 내에서 좌에서 우로 Swipe 시 이전 페이지로 이동되어야 함

[현재증상]
앱 내 모든 2depth 이상 페이지 화면 영역 내에서 좌에서 우로 Swipe 시 이전 페이지로 이동되지 않음

**Comment by minkyuuuu** [comment]
구조상 프로젝트 내 화면 전체 Activity에 대하여 작업및 테스트가 필요하여 일정산정 어려움

**Comment by MinJaeHun** [comment]
[12.29] C&M 추가 협의를 통해 closing 재결정 예정

**Comment by benjamincho** [comment]
16/01/21 회의에서 고객사와 협의하여 이슈종료합니다.

**Comment by MinJaeHun** [comment]
[01.29] 해당 이슈 SKIP 확정, QC closing
