### ISSUE TITLE
86. 셋탑박스 구매 비밀번호 등록 페이지 내 구매 신규 비밀번호 및 입력확인 비밀번호 불일치 하게 입력 시 안내 문구가 표시되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#17]
[보고일자]
2015.12.11

[빌드버전]
0.8

[재현경로]
1. 셋탑박스 연동하기
2. 구매 비밀번호 등록 페이지
3. 구매 비밀번호 신규설정과 구매 비밀번호 입력확인을 다르게 입력

[예상결과]
불일치 시 ‘인증번호 혹은 확인입력이 일치하지 않습니다.' 안내문구 노출 되어야 함

[현재증상]
셋탑박스 구매 비밀번호 등록 페이지 내 구매 신규 비밀번호 및 입력확인 비밀번호의 일치, 불일치 여부에 따른 문구가 표시되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
