### ISSUE TITLE
91. 구매 비밀번호 등록 페이지 내 비밀번호 미입력 시 다음단계 버튼이 비활성화 되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#18]
[보고일자]
2015.11.18

[빌드버전]
0.8

[재현경로]
1. 셋탑박스 연동하기
2. 구매 비밀번호 등록 페이지
3. 비밀번호 미입력

[예상결과]
구매 비밀번호 등록 페이지 내 비밀번호 미입력 시 다음단계 버튼이 비활성화 되어야 함

[현재증상]
구매 비밀번호 등록 페이지 내 비밀번호 미입력 시 다음단계 버튼이 비활성화 되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC 의견 : 비활성화 상태일 경우 버튼 색상 회색으로 변경 필요 (등록 쉬초 버튼과 동일하게 구현 필요)

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.26] QC confirm / closing
