### ISSUE TITLE
103. VOD 시청목록, VOD 찜목록 타이틀, 날짜(시간) 위치가 시나리오와 상이 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#22]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. 레이어 메뉴 호출 > 마이 C&M
2. VOD 시청목록, VOD 찜목록 탭
3. 시청목록, 찜목록 내용 위치 확인

[예상결과]
VOD 시청목록, VOD 찜목록 타이틀, 시청/찜한 날짜(시간) 위치가 시나리오 대로 위치하여야 함

타이틀 / 시청(찜한) 날짜
           시청(찜한) 시간

순으로 표시 되어야 함

[현재증상]
VOD 시청목록, VOD 찜목록 타이틀, 시청/찜한 날짜(시간) 위치가 시나리오와 상이 함

시청(찜한) 날짜 / 타이틀
시청(찜한) 시간

순으로 표시 됨

**Comment by Kimwoodam** [comment]
@MinJaeHun 테스터분들과 회의 시 디자인가이드 우선시 하기로 이야기 된 부분입니다. 확인 부탁드립니다.

**Comment by MinJaeHun** [comment]
[12.29] 최종 GUI flipbook 전달 후 C&M 검토를 통해 closing 재결정 예정

**Comment by MinJaeHun** [comment]
[2016.01.21] QC confirm / closing
