### ISSUE TITLE
104. 마이 C&M 페이지 내 구매, 시청, 찜목록 Swipe 하여 삭제 버튼 노출 시 목록 좌로 밀리지 않아야 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#23]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. 레이어 메뉴 호출 > 마이 C&M
2. 구매, 시청, 찜목록 우에서 좌로 Swipe
3. 삭제 버튼 노출 시 목록 확인

[예상결과]
목록 Swipe 시 삭제 버튼이 목록 위로 Over되는 형태로 구현되어야 함
* EPG와 시나리오 다름

[현재증상]
마이 C&M 페이지 내 구매, 시청, 찜목록 Swipe 하여 삭제 버튼 노출 시 목록 좌로 밀리지 않아야 함

**Comment by minkyuuuu** [comment]
고객센터 안내 페이지 내 고객센터 전화번호 링크처리 되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 해당 이슈는 테스터분들과 회의 시 디자인 가이드를 따르며 해당 이슈 Closing 처리 하기로 한 이슈 입니다. 확인 부탁 드립니다.

**Comment by MinJaeHun** [comment]
[12.29] 미팅을 통해 closing 결정 (캐스트이즈, GT)
