### ISSUE TITLE
105. VOD 구매 완료 후 구매완료 팝업에서 확인 버튼 클릭 시 VOD 즉시 시청 되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#24]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. VOD 상세 페이지 진입
2. 구매하기 버튼 클릭
3. 구매 완료 후 구매팝업 호출 상태
4. 구매팝업 내 확인 버튼 클릭

[예상결과]
VOD 구매 완료 후 구매완료 팝업에서 확인 버튼 클릭 시 VOD 즉시 시청 되어야 함

[현재증상]
VOD 구매 완료 후 구매완료 팝업에서 확인 버튼 클릭 시 VOD 즉시 시청 되지 않음

**Comment by MinJaeHun** [comment]
[12.29] 플레이어 이슈는 주요 오류사항 처리 후 플레이어 제어 범위 검토하여 재협의

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
