### ISSUE TITLE
109. 성인인증 완료 상태에서 셋탑박스 페어링 해지(셋탑박스 재연동) 시 19세 제한 VOD 딤처리되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#25]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. 성인인증 완료 상태
2. 셋탑박스 페어링 해지(셋탑박스 재연동 버튼 클릭 후 확인)
3. 19세 제한 포스터 딤처리 확인

[예상결과]
성인인증 완료 상태에서 셋탑박스 페어링 해지(셋탑박스 재연동) 시 성인인증 해제 되므로 19세 제한 컨텐츠 딤처리 되어야 함

[현재증상]
성인인증 완료 상태에서 셋탑박스 페어링 해지(셋탑박스 재연동) 시 19세 제한 VOD 딤처리되지 않음
* VOD 상세페이지 진입 및 성인 카테고리 진입은 되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.26] QC confirm / closing
