### ISSUE TITLE
111. 찜목록에서 목록 Swipe하여 찜해제 시 목록에서는 삭제 되나 VOD 상세 페이지에서 찜해제 되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#26]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. VOD 상세 페이지 내에서 찜하기 클릭
2. 찜목록에서 해당 VOD 찜해제
3. VOD 상세 페이지 내 찜해제 여부 확인

[예상결과]
찜목록에서 찜해제 시 VOD 상세 페이지 내의 찜하기도 해제 되어야 함
* 페어링 된 셋탑에서 찜목록 해제 시에도 모바일 앱 상세 페이지 찜하기 버튼 해제되어야 함 (찜목록에서는 삭제 됨)

[현재증상]
찜목록에서 목록 Swipe하여 찜해제 시 목록에서는 삭제 되나 VOD 상세 페이지에서 찜해제 되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC 의견 : 모바일에서는 정상적으로 찜해제되지만, 셋탑에서 찜목록 삭제 시 VOD 상세 페이지에서 찜 해제되지 않음
[2016.01.10] 찜 해제 시 시스템으로 찜 해제 정보 전달하는지 확인 부탁 드립니다.

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.02.01 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.02.01] QC confirm / closing
