### ISSUE TITLE
116. 고객센터 안내 페이지 내 고객센터 전화번호 링크처리 되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#27]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. 레이어 메뉴 호출 > 설정 페이지
2. 고객센터 안내 페이지

[예상결과]
고객센터 안내 페이지 내 고객센터 전화번호 링크처리 되어 클릭하여 전화 가능하여야 함

[현재증상]
고객센터 안내 페이지 내 고객센터 전화번호 링크처리 되지 않음

**Comment by minkyuuuu** [comment]
고객센터 안내 페이지 내 고객센터 전화번호 링크처리 되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 해당 이슈는 서버의 html 데이터 포맷 수정이 필요한 사항으로 서버쪽 확인 부탁 드립니다.

**Comment by MinJaeHun** [comment]
[12.29] HTML 수정 메일 재전송 후 closing 예정

**Comment by MinJaeHun** [comment]
[2016.01.21] QC confirm / closing
