### ISSUE TITLE
120. 카테고리 내 특정 포스터 목록 타이틀 1~2글자만 표시 됨

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#28]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. 영화 카테고리 > 이달의 추천 VOD(특집)
2. 포스터 목록 하단 타이틀 확인

[예상결과]
카테고리 내 특정 포스터 목록 타이틀 표시 되어야 하며 길 경우 줄임표시 되어야 함

[현재증상]
카테고리 내 특정 포스터 목록 타이틀 1~2글자만 표시 됨
(ex : 영화 > 이달의 추천 VOD(특집) > 뷰티인사이드, 제7기사단, 미쓰와이프…)

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.26] QC confirm / closing
