### ISSUE TITLE
127. 채널 장르 GNB 내 장르 선택 된 장르에 포커스 유지되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#29]
[보고일자]
2015.11.19

[빌드버전]
0.81

[재현경로]
1. 채널가이드, 리모컨 페이지
2. 채널 장르 선택 GNB 클릭
3. 임의의 장르 선택
4. GNB 클릭하여 포커스 상태 확인

[예상결과]
채널 장르 GNB 내 장르 선택 된 장르에 포커스 유지되어야 함

[현재증상]
채널 장르 GNB 내 장르 선택 된 장르에 포커스 유지되지 않음
채널가이드, 리모컨 페이지

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
