### ISSUE TITLE
134. 미리보기 3분 이상 시청되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#30]
[보고일자]
2015.11.20

[빌드버전]
0.81

[재현경로]
1. 미리보기 존재하는 VOD 상세 페이지 진입
2. 미리보기 시청시간 확인

[예상결과]
설정 된 미리보기 시간에 맞게 미리보기 시청 가능 하여야 함

[현재증상]
미리보기 3분 이상 시청되지 않음
실제 VOD 메타 데이터에서는 3분이상으로 보여주고 있음
(ex : 뷰티 인 사이드 - 5분으로 보여줌)

**Comment by minkyuuuu** [comment]
1. 플레이어 이슈 여부를 검토할 수 있게 자세한 재현증상 코멘트 추가 요청필요
2. 스트리밍 서버 관련 이슈여부 검토 필요

**Comment by MinJaeHun** [comment]
[12.29] 플레이어 이슈는 주요 오류사항 처리 후 플레이어 제어 범위 검토하여 재협의

**Comment by MinJaeHun** [comment]
[16.02.02] 제외 결정
