### ISSUE TITLE
135. 시리즈 VOD 상세 페이지 내에서 현재 회차 찜하기 후 다른 회차 이동 시 찜하기 버튼 찜 상태로 유지 됨

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#31]
[보고일자]
2015.11.20

[빌드버전]
0.81

[재현경로]
1. 시리즈 VOD 상세 페이지
2. 찜하기 후 다른 회차 이동
3. 찜하기 버튼 상태 확인

[예상결과]
시리즈 VOD 상세 페이지 내에서 회차별로 찜하기 각각 설정 가능 하여야 함

[현재증상]
시리즈 VOD 상세 페이지 내에서 현재 회차 찜하기 후 다른 회차 이동 시 찜하기 버튼 찜 상태로 유지 됨
버튼 클릭 시 찜하기는 되나 버튼 상태가 변경되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
