### ISSUE TITLE
139. 셋탑박스 연동 해지 시에도 찜한 VOD 상세 페이지 내 찜하기 버튼 찜해제로 변경되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#32]
[보고일자]
2015.11.20

[빌드버전]
0.81

[재현경로]
1. VOD 상세 페이지 내 찜하기 상태
2. 셋탑박스 연동 해지
3. VOD 상세 페이지 내 찜하기 버튼 확인

[예상결과]
셋탑박스 연동 해지 시 찜한 앱 내 찜하기 해제 및 목록 삭제 되어야 함

[현재증상]
셋탑박스 연동 해지 시에도 찜한 VOD 상세 페이지 내 찜하기 버튼 찜해제로 변경되지 않음
찜 목록에서는 사라지며, 셋탑 재연동 시 찜하기 버튼 해제 됨

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.02.01 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[16.02.01] QC confirm / closing
