### ISSUE TITLE
142. VOD 구매, 시청, 찜목록 롱탭 후 Swipe 시 간헐적으로 삭제 및 찜해제 버튼 노출되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#33]
[보고일자]
2015.11.20

[빌드버전]
0.81

[재현경로]
1. 마이 C&M > VOD 구매, 시청, 찜목록
2. 목록 롱탭 후
3. 목록 우에서 좌로 Swipe
4. 삭제, 찜해제 버튼 노출여부 확인

[예상결과]
VOD 구매, 시청, 찜목록 롱탭 시 기능 동작에 이상 발생하지 않아야 함

[현재증상]
VOD 구매, 시청, 찜목록 롱탭 후 Swipe 시 간헐적으로 삭제 및 찜해제 버튼 노출되지 않음

**Comment by MinJaeHun** [comment]
[12.29] 사용성 문제, 주요 오류사항 처리 후 시간 여유가 있을 경우 점검

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.26] QC confirm / closing
