### ISSUE TITLE
182. 성인 검색 제한 Off 상태에서 셋탑 연동 해제 후 재연동 시 검색제한 On으로 변경되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#37]
[보고일자]
2015.11.24

[빌드버전]
0.9

[재현경로]
1. 성인인증 완료 상태
2. 성인 검색 제한 Off 설정
3. 셋탑박스 페어링 해지
4. 성인 검색 제한 상태 확인

[예상결과]
성인 검색 제한 Off 상태에서 셋탑 연동 해제 후 재연동 시 성인인증도 해제 되어야 하며, 검색제한 On으로 변경되어야 함

[현재증상]
성인 검색 제한 Off 상태에서 셋탑 연동 해제 후 재연동 시 성인인증은 해제 되나, 검색 제한 상태 On으로 변경되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
