### ISSUE TITLE
187. VOD 시청 종료 시 자동으로 VOD 상세 페이지로 이동되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#38]
[보고일자]
2015.11.24

[빌드버전]
0.9

[재현경로]
1. VOD 상세 페이지
2. VOD 시청 후 종료
3. 상세 페이지 이동여부 확인

[예상결과]
VOD 시청 종료 시 자동으로 VOD 상세 페이지로 이동되어야 함

[현재증상]
VOD 시청 종료 시 자동으로 VOD 상세 페이지로 이동되지 않음
* 미리보기 시에도 동일 처리 필요

**Comment by MinJaeHun** [comment]
[12.29] 플레이어 이슈는 주요 오류사항 처리 후 플레이어 제어 범위 검토하여 재협의

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
