### ISSUE TITLE
197. 구매 비밀번호 입력 팝업 내 시청 가능 기간 우측 정렬되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#39]
[보고일자]
2015.11.24

[빌드버전]
0.9

[재현경로]
1. VOD 상세 페이지
2. 구매 페이지 내 결제하기 버튼 클릭
3. 구매 비밀번호 입력 팝업 내 시청기간 정렬 상태 확인

[예상결과]
구매 비밀번호 입력 팝업 내 시청 가능 기간 우측 정렬되어야 함

결제방법[부가세 별도]          20,000원
시청기간                                3일

와 같이 정렬 필요

[현재증상]
구매 비밀번호 입력 팝업 내 시청 가능 기간 우측 정렬되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
