### ISSUE TITLE
201. 시리즈 녹화 가능 한 경우 이번 회차만 녹화하기, 이번 회차부터 전체 녹화/예약하기 버튼이 노출되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#40]
[보고일자]
2015.11.24

[빌드버전]
0.9

[재현경로]
1. PVR 셋탑 페어링 
2. 채널 가이드 > 시리즈 방송 채널 즉시 녹화
3. 녹화 팝업 노출 여부 확인

[예상결과]
시리즈 녹화 가능 한 경우 이번 회차만 녹화하기, 이번 회차부터 전체 녹화/예약하기 버튼이 노출되어야 함

[현재증상]
시리즈 녹화 가능 한 경우 이번 회차만 녹화하기, 이번 회차부터 전체 녹화/예약하기 버튼이 노출되지 않음

**Comment by MinJaeHun** [comment]
[12.29] 시스템 로그 확인 후 결과를 가지고 대안 재협의

**Comment by MinJaeHun** [comment]
[16.02.01] QC confirm / closing
