### ISSUE TITLE
211. 공지사항 목록 테스트용으로 노출 됨

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#43]
[보고일자]
2015.11.25

[빌드버전]
0.91

[재현경로]
1. 레이어 메뉴 호출 > 설정
2. 공지사항 목록 확인

[예상결과]
라이브 런칭 전에 정식 공지사항이 등록 되어야 함

[현재증상]
공지사항 목록 테스트용으로 노출 됨

**Comment by minkyuuuu** [comment]
서버에서 내려오는 공지사항 목록이 테스트용 리스트가 내려옴

**Comment by Kimwoodam** [comment]
@MinJaeHun 해당 이슈는 서버 수신 데이터 수정이 필요한 사항으로 서버쪽 확인 부탁 드립니다.

**Comment by MinJaeHun** [comment]
[12.29] 미팅을 통해 closing 결정 (캐스트이즈, GT)
