### ISSUE TITLE
214. 시청 목록 내에서 VOD 목록 선택하여 VOD 상세 페이지 진입 후 뒤로가기 시 시청목록 페이지로 복귀되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#44]
[보고일자]
2015.11.25

[빌드버전]
0.91

[재현경로]
1. VOD 시청목록 > 목록 클릭
2. VOD 상세 페이지 진입
3. 뒤로가기 버튼 클릭
4. 시청목록으로 복귀 여부 확인

[예상결과]
시청 목록 내에서 VOD 목록 선택하여 VOD 상세 페이지 진입 후 뒤로가기 시 시청목록 페이지로 복귀되어야 함

[현재증상]
시청 목록 내에서 VOD 목록 선택하여 VOD 상세 페이지 진입 후 뒤로가기 시 시청목록 페이지로 복귀되지 않음
구매목록, 찜목록은 정상 동작 함

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
