### ISSUE TITLE
224. 페어링 해지 후 셋탑 재연동 시 시청목록 초기화되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#45]
[보고일자]
2015.11.26

[빌드버전]
0.92

[재현경로]
1. 시청목록 존재 상태
2. 셋탑 페어링 해지 및 재연동
   (동일 셋탑, 다른 셋탑)

[예상결과]
페어링 해지 후 셋탑 재연동 시 시청목록 초기화되어야 함
* 찜목록 시나리오와 동일한 형태로 구현 요망

[현재증상]
페어링 해지 후 셋탑 재연동 시 시청목록 초기화되지 않음
동일 셋탑 재연동 및 다른 셋탑 연동 시 동일 하게 초기화되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
