### ISSUE TITLE
226. 시리즈 VOD 상세 페이지 회차 목록 내 우측 화살표 비정상 동작 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#46]
[보고일자]
2015.11.26

[빌드버전]
0.92

[재현경로]
1. 시리즈 VOD 상세 페이지
2. 제일 좌측 회차에 스크롤 위치 (우측 화살표 [▶] 상태)
3. 우측 회차로 스크롤 이동 시 제일 우측 회차에 위치하지 않아도 우측 화살표 [▷]로 변경 됨

[예상결과]
시리즈 VOD 상세 페이지 회차 목록 내 우측 화살표 정상 동작 해야 함

[현재증상]
시리즈 VOD 상세 페이지 회차 목록 내 우측 화살표 비정상 동작 함

**Comment by MinJaeHun** [comment]
[2016.01.12] QC confirm / closing
