### ISSUE TITLE
247. 특정 채널 선호채널 등록 시에도 선호채널 목록에 노출되지 않음 

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#51]
[보고일자]
2015.11.28

[빌드버전]
0.95

[재현경로]
1. 채널가이드 페이지
2. 특정 채널(ex : CH. 8, 14, 40...) 선호채널 등록
3. 장르 선택 GNB 클릭 후 선호채널 진입

[예상결과]
선호채널 등록 시 선호채널 목록에 모두 노출 되어야 함

[현재증상]
특정 채널 선호채널 등록 시에도 선호채널 목록에 노출되지 않음 
(ex : CH. 8, 14, 40...)

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
