### ISSUE TITLE
248. 사이드 메뉴 내 페이지 이동 후 뒤로가기 시 사이드 메뉴 사라짐

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#52]
[보고일자]
2015.11.28

[빌드버전]
0.95

[재현경로]
1. 사이드 메뉴 펼침
2. 셋탑박스 재연동, 채널가이드, 리모컨, 녹화, 마이 씨앤앰, 설정, 서비스 이용약관 등 메뉴 클릭 하여 화면 이동
3. 이동 화면에서 이전버튼 클릭하여 메인으로 이동

[예상결과]
사용자 편의를 위하여 사이드 메뉴 내 페이지 이동 후 뒤로가기 시 사이드 메뉴 유지되어야 함

[현재증상]
사이드 메뉴 내 페이지 이동 후 뒤로가기 시 사이드 메뉴 사라짐

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
