### ISSUE TITLE
254. 채널가이드 내 방송 녹화 예약 및 취소 시 로딩팝업이 2~3회가량 반복 노출됨 

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#54]
[보고일자]
2015.11.28

[빌드버전]
0.95

[재현경로]
1. PVR 셋탑 페어링 상태
2. 채널가이드 > 일간 방송 목록
3. 프로그램 녹화 예약 및 예약취소
4. 로딩팝업 확인

[예상결과]
채널가이드 내 방송 녹화 예약 및 취소 시 로딩팝업이 2~3회가량 반복 노출되지 않아야 함

[현재증상]
채널가이드 내 녹화 예약 및 취소 시 로딩팝업이 2~3회가량 반복 노출됨 
녹화불가 방송의 경우 녹화 불가 팝업과 로딩팝업이 번갈아가며 노출 됨

**Comment by MinJaeHun** [comment]
[12.29] 강제 지연 시간을 위해 로딩바 추가 적용한 상태
[12.29] 시스템 로그 확인 후 결과를 가지고 대안 재협의

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.02.01 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[16.02.01] QC cconfirm / closing
