### ISSUE TITLE
257. 녹화예약관리 페이지 내 시리즈 녹화예약 목록에서 Swipe 시 페이지 정보 노출되지 않음.

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#55]
[보고일자]
2015.11.29

[빌드버전]
0.96

[재현경로]
1. 시리즈 녹화물 예약 상태
2. 녹화 >  녹화 예약 목록 선택 > 히든싱어4 > Swipe 후 페이지 정보 확인

[예상결과]
페이지 정보가 노출되어야함.

[현재증상]
녹화예약관리 페이지 내 시리즈 녹화예약 목록에서 Swipe 시 페이지 정보 노출되지 않음.

**Comment by Kimwoodam** [comment]
15.12.22  기획 이해도 차이로 Closing 처리 하기로 테스터 분들과 협의한 내용입니다.

확인 부탁 드립니다.

**Comment by MinJaeHun** [comment]
[2015.12.22] issue closng / 오류 아닌 것으로 협의
