### ISSUE TITLE
274. 셋탑 전원 OFF상태일 경우 녹화 페이지 진입 시 에러팝업 구현되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#61]
[보고일자]
2015.11.30

[빌드버전]
0.97

[재현경로]
1. 페어링 된 셋탑 전원 Off상태
2. 레이어 메뉴 호출 > 녹화 페이지 진입

[예상결과]
셋탑 전원 OFF상태일 경우 녹화 페이지 진입 시 에러팝업 구현되어야 함

[현재증상]
셋탑 전원 OFF상태일 경우 녹화 페이지 진입 시 에러팝업 구현되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.02.01 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[16.02.01] QC confirm / closing
