### ISSUE TITLE
282. VOD 미리보기 시 시청목록에 목록 추가 됨

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#64]
[보고일자]
2015.12.01

[빌드버전]
0.98

[재현경로]
1. VOD 상세 페이지 내 미리보기 시청
2. VOD 시청목록 확인

[예상결과]
VOD 미리보기 시 시청목록에 목록 추가되지 않아야 함

[현재증상]
VOD 미리보기 시 시청목록에 목록 추가 됨

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
