### ISSUE TITLE
283. VOD 시청 시(가로보기 상태) 상하 반전되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#65]
[보고일자]
2015.12.01

[빌드버전]
0.98

[재현경로]
1. VOD 시청 중(가로보기 상태)
2. 상하 반전 동작 확인

[예상결과]
VOD 시청 시(가로보기 상태) 상하 반전되어야 함

[현재증상]
VOD 시청 시(가로보기 상태) 상하 반전되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
