### ISSUE TITLE
287. 녹화물 목록 내 시리즈 녹화물 삭제 불가 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#67]
[보고일자]
2015.12.01

[빌드버전]
0.98

[재현경로]
1. PVR 셋탑 페어링 상태
2. 시리즈 녹화물 존재 상태
3. 녹화 페이지 > 녹화물 목록 탭
4. 시리즈 녹화 목록 클릭 및 Swipe 시도

[예상결과]
녹화물 목록 내 시리즈 녹화물 클릭 시 상세 목록 페이지로 이동 되어야 하며 상세 목록 Swipe하여 삭제 버튼 클릭 시 단편/시리즈 녹화물 삭제가 되어야 함

[현재증상]
녹화물 목록 내 시리즈 녹화물 삭제 불가 함

**Comment by MinJaeHun** [comment]
[16.02.02] QC confirm / closing
