### ISSUE TITLE
288. 프로그램 검색 목록 좌측 선호채널 등록 아이콘 클릭 시 동일 채널 동시에 선호채널 등록상태로 아이콘 변경되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#68]
[보고일자]
2015.12.01

[빌드버전]
0.98

[재현경로]
1. 검색 > 프로그램명 검색(ex : 성인)
2. 210번 채널만 노출 됨
3. 좌측 선호채널 등록 아이콘 클릭
4. 동일 채널의 아이콘 변경 여부 확인

[예상결과]
프로그램 검색목록에 노출 된 항목이 동일 채널일 경우 선호채널 아이콘 클릭 시 모든 동일 채널의 선호채널 아이콘이 변경 되어야 함

[현재증상]
프로그램 검색 목록 좌측 선호채널 등록 아이콘 클릭 시 동일 채널 동시에 선호채널 등록상태로 아이콘 변경되지 않음
채널 목록 스크롤 시 적용 됨

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
