### ISSUE TITLE
290. VOD 시청 중 WiFi 망에서 LTE, 3G망으로 변경 될 시 팝업 발생하지 않으며 VOD 재생 종료 되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#69]
[보고일자]
2015.12.02

[빌드버전]
0.99

[재현경로]
1. WiFi 망 상태에서 VOD 재생 중
2. LTE, 3G로 전환

[예상결과]
VOD 시청 중 WiFi 망에서 LTE, 3G망으로 변경 될 시 팝업 발생며 VOD 재생 종료되어야 함

[현재증상]
VOD 시청 중 WiFi 망에서 LTE, 3G망으로 변경 될 시 팝업 발생하지 않으며 VOD 재생 종료 되지 않음

**Comment by MinJaeHun** [comment]
[12.29] 이전 미팅 시 김우담 과장 협의하여 가이드 범위 결정. 팝업 문구는 확정 필요

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by Kimwoodam** [comment]
[QC Comment ]
Wifi 접속 상태에서 VOD 재생 후 재생 도중 WiFi 해지 시 팝어 발생하며 재생 종료 되나,
VOD 재생 상태에서 WiFi 접속 후 해지 시 재생 종료되지 않음

**Comment by MinJaeHun** [comment]
[01.12] QC
WiFi 접속 상태에서 VOD 재생 후 재생 도중 WiFi 접속 해지 시 팝업 발생하며, 재생 종료되지만, VOD 재생 상태에서 VOD 재생 상태에서 WiFi 접속 후 해지 시 재생 종료 종료되지 않음

**Comment by Kimwoodam** [comment]
[01.12] QC
VOD 재생 상태에서 WiFi 접속 후 해지 시 재생 종료 팝업 발생 되나 백그라운드에서 재생 종료되지 않음 
팝업도 중복 발생하는 것으로 보임. 한번만 발생하도록 수정 필요

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.02.01 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[16.02.01] QC confirm / closing
