### ISSUE TITLE
297. 레이어메뉴 버튼 빠르게 연속 클릭 시 메뉴 중복으로 발생 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#72]
[보고일자]
2015.12.08

[빌드버전]
1.04

[재현경로]
1. 메인 페이지
2. 좌측 상단 레이어 메뉴 버튼 빠르게 클릭

[예상결과]
레이어 메뉴 중복발생하지 않아야 함

[현재증상]
레이어메뉴 버튼 빠르게 연속 클릭 시 메뉴 중복으로 발생 함

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
