### ISSUE TITLE
298. 무료 VOD 가격정보 내 '무료시청'으로 표기 됨

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#73]
[보고일자]
2015.12.08

[빌드버전]
1.04

[재현경로]
1. 무료 VOD 상세 페이지
2. 가격정보 확인

[예상결과]
무료 VOD 가격정보 내 '무료' 로 표기 되어야 함

[현재증상]
무료 VOD 가격정보 내 '무료시청'으로 표기 됨

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
