### ISSUE TITLE
299. 검색 페이지 내 '프로그램 명 검색'으로 표기 됨

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#74]
[보고일자]
2015.12.08

[빌드버전]
1.04

[재현경로]
1. 검색 페이지
2. TV 프로그램 명 검색 탭 문구 확인

[예상결과]
검색 페이지 내 'TV 프로그램 명 검색'으로 표기 되어야 함

[현재증상]
검색 페이지 내 '프로그램 명 검색'으로 표기 됨

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.28] QC confirm / closing
