### ISSUE TITLE
300. 19세 제한 포스터 순위 표시 및 프로모션 스티커 딤처리에 오버되어 표시 되지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#75]
[보고일자]
2015.12.08

[빌드버전]
1.04

[재현경로]
1. 성인인증 미진행 상태
2. 인기순위 및 기타 카테고리 페이지
3. 19세 제한 포스터 딤처리 및 순위, 프로모션 스티커 노출 상태 확인

[예상결과]
19세 제한 포스터 순위 표시 및 프로모션 스티커 딤처리에 오버되어 표시 되어야 함

[현재증상]
19세 제한 포스터 순위 표시 및 프로모션 스티커 딤처리에 오버되어 표시 되지 않음
딤 아래로 처리 되어 눈에 띄지 않음

**Comment by MinJaeHun** [comment]
[2015.12.28] QC : 인기순위 표시 딤처리 위로 오버되지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 수정 완료 및 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.05] QC confirm / closing
