### ISSUE TITLE
303. 앱 실행 중 네트워크 끊겼을 시 앱 종료를 권고하는 팝업이 발생하지 않음

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#77]
[보고일자]
2015.12.10

[빌드버전]
1.05

[재현경로]
1. 앱 실행 중
2. 데이터 통신 차단(ex : 비행기 모드)
3. 앱 동작 확인

[예상결과]
앱 실행 중 네트워크 끊겼을 시 앱 종료를 권고하는 팝업이 발생되어야 함
* 아이폰과 동일한 시나리오로 구현 요청

[현재증상]
앱 실행 중 네트워크 끊겼을 시 앱 종료를 권고하는 팝업이 발생하지 않음

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.11 릴리즈 노트 배포 하였습니다.

**Comment by Kimwoodam** [comment]
[ QC Comment ]
팝업 정상 발생하나 2회 중복으로 발생 됨 (1회만 발생하도록 수정 필요)

**Comment by Kimwoodam** [comment]
@MinJaeHun 16.01.18 릴리즈 노트 배포 하였습니다.

**Comment by MinJaeHun** [comment]
[2016.01.19] QC confirm / closing
