### ISSUE TITLE
304. 특정 단말기 앱 비정상 동작 함

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#78]
[보고일자]
2015.12.11

[빌드버전]
1.05

[재현경로]
폰 종류 : 갤럭시 S6
-. 모델번호 : SM-G920K (KT 가입폰)
-. 안드로이드 버전 : 5.1.1

[예상결과]
단말에 관계없이 앱 정상 동작 하여야 함
* 원인 분석 필요

[현재증상]
특정 단말기 앱 비정상 동작 함

**Comment by Kimwoodam** [comment]
황민규 부장님께서 수정(15.12.22)하였다고 이야기 들은 이슈입니다. 확인 부탁 드립니다.

**Comment by minkyuuuu** [comment]
특정 셋탑에서 발생하는 현상으로 서버에서 현재 2개의 SO에 해당하는 데이타만 내려보내고 있어서 발생된 현상.
특정 셋탑이 2개의 SO에 포함되지 않음.
서버 이슈로 colse함.

**Comment by minkyuuuu** [comment]
해당 이슈는 방금 close 했습니다.
