### ISSUE TITLE
305. LG 단말기 Soft key UI에 가려 하단 버튼 잘림

### ISSUE THREAD

**Issue by minkyuuuu** [LambertPark/A_NScreen#79]
[보고일자]
2015.12.11

[빌드버전]
1.05

[재현경로]
1. LG 단말기
2. 셋탑 페어링 및 구매 시 버튼 UI 확인

[예상결과]
LG 단말기 Soft key UI에 가려지지 않도록 하단 버튼 위치 조정 되어야 함

[현재증상]
LG 단말기 Soft key UI에 가려 하단 버튼 잘림

**Comment by minkyuuuu** [comment]
ScrollView로 처리함.

**Comment by Kimwoodam** [comment]
[ QC Comment]
기본적으로 STB 연동 부분에서는 하단 버튼은 다 짤립니다.
뭐 스크롤이 먹어서 누를수는 있지만 마지막 페이지는 스크롤도 되지 않습니다.
확인 부탁 드립니다.

**Comment by minkyuuuu** [comment]
"STB 연동 마지막 완료 페이지에서 확인 버튼 잘 안보임" - ScrollView 추가 처리.

**Comment by Kimwoodam** [comment]
강원태 대리가 1월 20일 CNM 전만기 과장에게 이슈 수정에 대하여 확인 요청 상태입니다.

**Comment by MinJaeHun** [comment]
[16.01.29] QC confirm / closing
